/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mongodbapp;

import Anime._Anime;
import Conection.MongoConnect;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Label;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author osouza
 */
public class Lista extends javax.swing.JFrame {

    /**
     * Creates new form Lista
     */
    public boolean logado = false;
    public String user = "brabo";
    public String pass = "000";
    public Lista() {
        initComponents();
        this.setLocationRelativeTo(null);
        //populatioTableAnimes();
        
        listaAnime.setOpaque(true);
        listaAnime.setFillsViewportHeight(true);
        listaAnime.setBackground(new Color(112, 123, 124));
                
        listaAnime.getTableHeader().setFont(new Font("Fira Code Medium", Font.PLAIN, 14));
        //listaAnime.getTableHeader().setBackground(Color.YELLOW);
        
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(239, 198, 46));
        
        listaAnime.setShowGrid(true);
                
        
        for (int i = 0; i < listaAnime.getModel().getColumnCount(); i++) {
            listaAnime.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logar = new javax.swing.JButton();
        addAnime = new javax.swing.JButton();
        atualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaAnime = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de Animes");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        logar.setBackground(new java.awt.Color(51, 51, 51));
        logar.setFont(new java.awt.Font("Fira Code Medium", 0, 14)); // NOI18N
        logar.setForeground(new java.awt.Color(255, 255, 255));
        logar.setText("Logar");
        logar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        logar.setBorderPainted(false);
        logar.setFocusable(false);
        logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logarActionPerformed(evt);
            }
        });

        addAnime.setBackground(new java.awt.Color(51, 51, 51));
        addAnime.setFont(new java.awt.Font("Fira Code Medium", 0, 14)); // NOI18N
        addAnime.setForeground(new java.awt.Color(255, 255, 255));
        addAnime.setText("Add Anime");
        addAnime.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        addAnime.setBorderPainted(false);
        addAnime.setEnabled(false);
        addAnime.setFocusable(false);
        addAnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAnimeActionPerformed(evt);
            }
        });

        atualizar.setBackground(new java.awt.Color(51, 51, 51));
        atualizar.setFont(new java.awt.Font("Fira Code Medium", 0, 14)); // NOI18N
        atualizar.setForeground(new java.awt.Color(255, 255, 255));
        atualizar.setText("Refresh");
        atualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        atualizar.setBorderPainted(false);
        atualizar.setEnabled(false);
        atualizar.setFocusable(false);
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addAnime, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addAnime, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        listaAnime.setFont(new java.awt.Font("Fira Code Medium", 0, 14)); // NOI18N
        listaAnime.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Episodios", "Temporadas", "Ano"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaAnime.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(listaAnime);
        if (listaAnime.getColumnModel().getColumnCount() > 0) {
            listaAnime.getColumnModel().getColumn(0).setResizable(false);
            listaAnime.getColumnModel().getColumn(0).setPreferredWidth(250);
            listaAnime.getColumnModel().getColumn(1).setResizable(false);
            listaAnime.getColumnModel().getColumn(2).setResizable(false);
            listaAnime.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logarActionPerformed
        // TODO add your handling code here:

        JTextField input1, input2;
        input1 = new JTextField(10);
        input2 = new JTextField(10);
        JPanel myp = new JPanel();
        myp.setLayout(new BoxLayout(myp, BoxLayout.Y_AXIS));
        myp.add(new Label("User: "));
        myp.add(input1);
        myp.add(new Label("Pass: "));
        myp.add(input2);

        int result = JOptionPane.showConfirmDialog(null, myp, "Logar", JOptionPane.OK_CANCEL_OPTION);
        if(result == JOptionPane.OK_OPTION)
        {
            if( input1.getText().equals(user) && input2.getText().equals(pass) )
            {
                JOptionPane.showMessageDialog(null, "Logado");
                populatioTableAnimes();
                logado = true;
                logar.setEnabled(!logado);
                addAnime.setEnabled(logado);
                atualizar.setEnabled(logado);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Senha ou Usuario errados!");
                System.out.println(input1.getText());
                System.out.println(input2.getText());
            }
        }

    }//GEN-LAST:event_logarActionPerformed

    private void addAnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAnimeActionPerformed
        // TODO add your handling code here:
        
        JTextField input1, input2, input3, input4;
        input1 = new JTextField(15);
        input2 = new JTextField(5);
        input3 = new JTextField(5);
        input4 = new JTextField(5);
        JPanel myp = new JPanel();
        myp.setLayout(new BoxLayout(myp, BoxLayout.Y_AXIS));
        myp.add(new Label("Nome: "));
        myp.add(input1);        
        myp.add(new Label("Episodios: "));
        myp.add(input2);
        myp.add(new Label("Ano: "));
        myp.add(input3);
        myp.add(new Label("Temporada: "));
        myp.add(input4);

        int result = JOptionPane.showConfirmDialog(null, myp, "Adicione seu Anime", JOptionPane.OK_CANCEL_OPTION);
        if(result == JOptionPane.OK_OPTION)
        {

            String[] anime = new String[]{input1.getText(), input2.getText(), input3.getText(), input4.getText()};
            
            for(String a : anime)
            {
                if(a.equals(""))
                {
                    JOptionPane.showMessageDialog(null, "Invalido, apresenta campos vazios!");
                    return;                    
                }                
            }
            
            MongoConnect.connectionToMongoDB(anime);
            
            populatioTableAnimes();
            
        }
        
    }//GEN-LAST:event_addAnimeActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:
        populatioTableAnimes();
    }//GEN-LAST:event_atualizarActionPerformed
    
    public void populatioTableAnimes()
    {
        
        DefaultTableModel tabAnimes = (DefaultTableModel) listaAnime.getModel();
        
        MongoConnect c = new MongoConnect();
                
        try{
            c.selectAllRecordsFromACollection().forEach((g) -> {
                tabAnimes.addRow(new Object[]{
                    g.getNome(), g.getEpisodios(), g.getTemporadas(), g.getAno()
                });
            });
        }catch(java.lang.NullPointerException e)
        {
            JOptionPane.showMessageDialog(null, "Erro ao popular tabela -> " + e);
        }
        
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAnime;
    private javax.swing.JButton atualizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaAnime;
    private javax.swing.JButton logar;
    // End of variables declaration//GEN-END:variables
}
